name: Python application with Github Actions

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  
    - name: Install dependencies
      run: |
        make install
        
  format-lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  
    - name: Format code
      run: |
        make format

    - name: Lint with pylint
      run: |
        make lint

    - name: Test with pytest
      run: |
        make test

    # - name: Build container
    #   run: |
    #     make build

    # - name: Run container
    #   run: |
    #     make run      
